spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root12345
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    prefix : classpath:/
    suffix: .html
    cache: false
    content-type: text/html
    enabled: true
    encoding: UTF-8
    mode: HTML5

server.port: 5000